### ISSUE TITLE
First line in test output obscured by heading

### ISSUE THREAD

**Issue by psdillon** [TheNexusAvenger/Nexus-Unit-Testing-Plugin#2]
The first line in the test output window is obscured by the test name:

![image](https://user-images.githubusercontent.com/3769461/87371813-7299c580-c5c9-11ea-8f78-e46203acd753.png)

**Comment by TheNexusAvenger** [comment]
For record-keeping purposes, this bug is known and was discussed in another issue in Nexus Unit Testing (https://github.com/TheNexusAvenger/Nexus-Unit-Testing/issues/4). I have seen this bug myself, and I hope that I can figure out a fix at some point.

**Comment by TheNexusAvenger** [comment]
This should now be addressed in the newest version.

**Comment by psdillon** [comment]
Awesome, thank you.
