### ISSUE TITLE
Horizontal scrolling bar for test window

### ISSUE THREAD

**Issue by ok-nick** [TheNexusAvenger/Nexus-Unit-Testing-Plugin#3]
In a small plugin window, it is currently impossible to read the entire test message without popping out the window and resizing it, or getting a better view by clicking on the tab.

![image](https://user-images.githubusercontent.com/25470747/115489484-42531780-a22a-11eb-9a63-5f60752f7649.png)

**Comment by TheNexusAvenger** [comment]
This request seems reasonable. Unfortunately, this request may stay in my backlog for a few months while I focus on other projects. Pull requests are open for anyone to implement this.

**Comment by TheNexusAvenger** [comment]
This is addressed in the `nexus-plugin-components` branch. I will close the issue once it is released.
